config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :controllers => { registrations: 'users/registrations' }

  shallow do
    resources :users, only: [:index, :show] do
      get 'follow'
      get 'unfollow'
      resources :posts do
        resources :comments
      end
    end
  end

  root to: 'posts#index'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :body, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.all.where(user_id: current_user.id)
    following_posts = current_user.following_users_posts
    following_posts.each do |following_post|
      @posts = following_post.or(@posts)
    end
    @posts.order(:updated_at)
  end

  def show
  end

  def new
    @post = Post.new
  end

  def edit
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      redirect_to @post, notice: 'Post was successfully created.'
    else
      render :new
    end
  end

  def update
    if @post.update(post_params)
      redirect_to @post, notice: 'Post was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy

    redirect_to user_posts_url(current_user), notice: 'Post was successfully destroyed.'
  end

  private
    def set_post
      @post = Post.find(params[:id])
    end

    def post_params
      params.require(:post).permit(:user_id, :body)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [@user, post] do |f| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: "btn btn-primary outline" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post, class: "btn btn-primary outline" %> 
<%= link_to 'Back', user_posts_path(current_user), class: "btn btn-primary outline" %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>
  <% @posts.each do |post| %>
  <div class="well">
    <article class="post-blog">
      <p class="posts_time"><%=l post.created_at, format: :br %></p>
      <p class="posts"><%= post.body%></p>
      <% if current_user.id == post.user.id %>
        <%= link_to I18n.t('link.show'), post_path(post) , class: "btn btn-primary outline"%>
        <%= link_to I18n.t('link.edit'), edit_post_path(post), class: "btn btn-primary outline" %>
        <%= link_to I18n.t('link.destroy'), post, method: :delete, class: "btn btn-primary outline", data: {:confirm => 'Are you sure?'}  %>
      <% end %>
      <%= link_to I18n.t('link.comments'), post_comments_path(post) , class: "btn btn-primary outline"%>
    </article>
  </div>
  <% end %>
<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post, user: @user %>

<%= link_to 'Back', user_posts_path, class: "btn btn-primary outline" %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post), class: "btn btn-primary outline" %> 
<%= link_to 'Back', user_posts_path(@user), class: "btn btn-primary outline" %>