config/routes.rb
Rails.application.routes.draw do
  devise_for :users , :controllers => { registrations: 'users/registrations' }

  shallow do
    resources :users, only: [:index, :show] do
      get 'follow'
      get 'unfollow'
      resources :posts do
        resources :comments
      end
    end
  end

  root to: 'posts#index'
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>MICROBLOG</title>
    <%= stylesheet_link_tag    'application', :media => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <script type="text/javascript">

  </script>
  <body>
    <nav class="navbar-inner">
      <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="brand">MICROBLOG</div>
            <ul class="nav nav-pills">
              <% if user_signed_in? %>
                <li class="active"><%= link_to 'Home', user_posts_path(current_user) %></li>
                <li class="active"><%= link_to 'New Post', new_user_post_path(current_user) %></li>
              <% end %>
                <li class="active"><%= link_to 'Find User', users_path %></li>
              <% if user_signed_in? %>
                <li class="active"><%= link_to 'Edit Account', edit_user_registration_path %></li>
              <% end %>
            </ul>
        </div>
      </div>
    </nav>
    <div id="main" role="main">
      <div class="container body-container">
        <% if user_signed_in? %>
          <%=t 'user.logged_in'%> <strong><%= current_user.name%></strong>
        <% end %>
        <br>
        <% if user_signed_in? %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'btn btn-danger btn-lg outline logout'  %>
        <% end %>
        <%= yield %>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>